# Generated by Django 2.2.7 on 2019-11-06 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Preventa', 'Preventa'), ('Soporte', 'Sopote'), ('Administración', 'Administración'), ('Implementación', 'Implementación'), ('Ventas', 'Ventas'), ('Compras', 'Compras')], max_length=15, verbose_name='Área')),
                ('position', models.CharField(choices=[('ING', 'Ingeniero'), ('Ejecutivo', 'Ejecutivo'), ('Administrativo', 'Administrativo')], max_length=15, verbose_name='Posición')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
